### ISSUE TITLE
Cannot pull the data set from LFS.

### ISSUE THREAD

**Issue by BenjaminChoou** [Joliezyx/causal_pathway_training#1]
When I try to fetch of pull the data set from LFS, condition as followed would happen.
```
Git LFS: (0 of 10 files) 0 B / 512.09 MB
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/Joliezyx/causal_pathway_training.git/info/lfs'
```
Could you fix it? I would appreciate if you do so.

**Comment by Joliezyx** [comment]
Hi, I checked Github's forum. And find an answer.

You've used up all your download bandwidth for the month. There's no way to undo that. You'll have to buy more data packs or wait until your next billing period. Hit up https://github.com/contact if you have more questions.

For the .mat files, please download at https://www.dropbox.com/sh/58br7t43h6y0sw7/AABWMWkNegHk4JxABFNqhRRGa?dl=0

**Comment by BenjaminChoou** [comment]
@Joliezyx Thank you for your kindness
